name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and test code
        run: |
          ./gradlew build
      - name: Deploy code
        uses: some-deploy-action@v1
        with:
          environment: production

